export const CHANGE_PERSON_NAME = "CHANGE_PERSON_NAME";
export const CHANGE_CAR_POWER = "CHANGE_CAR_POWER";
export const CHANGE_CAR_TYRE = "CHANGE_CAR_TYRE";
export const DELETE_CAR_TYRE = "DELETE_CAR_TYRE";